### PR TITLE
Examples for pay-trail webcomponent

### PR DESCRIPTION
**Pull request by Matsuuu**
## What type of Pull Request is this?

Check all the applicable.

- [ ] Refactor
- [ X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ X] Documentation Update

## Description

I've created a Web Component implementation of the PayTrail e2 api, which is framework agnostic. The source for it is here: https://github.com/Matsuuu/pay-trail

I'm hoping this package will be added to the PayTrail Github and released further under the paytrail npm namespace.

I've created 3 examples:

1 using just a html page with the import from a CDN
1 using a Lit Element project template (Could as well be react, vue etc).
1 Using a external api (Not calculating authcode in the frontend)

## Tests

- [ x] Not needed
- [ ] Unit tests added
- [ ] Integration tests added
- [ ] Visual verification done

## Code of Conduct

- [x ] I have read and agreed to the [community code of conduct][coc]. The sole intention of this pull request is to improve the project codebase.

[coc]: https://github.com/paytrail/.github/blob/master/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by Matsuuu** [comment]
I also threw in a React example too. :)

**Comment by nikoheikkila** [comment]
Haven't played much with the Web Components but being able to inject a dynamic `<paytrail>` element to the webpage would probably be of great value and interest to customers. Extra points for offering to calculate auth code on the backend.

I second adding a frontend library for this, but let's wait for Paytrail's say on this. 👍

**Comment by Matsuuu** [comment]
If this gets approved, I'll provide further documentation and examples and will expand the component further according to needs

**Comment by Matsuuu** [comment]
@Jipsukka  Any discussion in using this and further developing the Web Component approach at PayTrail?

I'd love to develop this further, but won't until this is given a green light and given a direction :)

**Comment by Jipsukka** [comment]
@Matsuuu Due summer vacations, we have not been able to meet to discuss this one yet. Some our key members are still on vacation this week, so unfortunately we might have to delay decisions bit longer.

**Comment by Matsuuu** [comment]
Cheers for the fast reply. Keep me updated here or via email about the discussions

**Comment by Matsuuu** [comment]
Nudging this one @Jipsukka . Has there been any progress with this?

**Comment by Jipsukka** [comment]
@Matsuuu Sorry it was long process, we had vacations and other matters. But here's the final verdict about this matter.
    
We can take third party developed repositories under our namespace and as part of our organization github, if the following criteria applies
    - Quality is accepted by Paytrail, mainly code quality, documentation, etc.
    - Repository offers some value to other developers, so it has some potential users
    - Everyone agrees the fact that repository in question is developed and maintained by third party.
    - Paytrail does not take responsibility to develop new features or fixing bugs as a priority.
    - Repository in question gets third-party tag and the `README.md` must state that it's not developed or maintained by Paytrail.
    - If repository stop being maintained, or falls behind in quality, we can remove repositories from our namespace. In this case, we will try to contact original developer first.
    
This particular repository meets the criteria in code quality, and we see this is something that might have potential users, thus meaning we are willing to take your `pay-trail`repository as part of Paytrail namespace, if you agree statements about third party developed application and the fact that we don't have knowledge nor priority to maintain such component. Web component is not part of our stack, and no one have deeper knowledge about it.
We however will remain control to accept pull requests, and developer of original repository will have get their pull requests accepted as long as code quality will remain good. We can accept pull requests by other developers with similar criteria, however we cannot test or verify that changes doesn't break anything. However, anyone is welcome to post their views about pull requests and give feedback. Also those repositories will require only one accepting review, compared to two in our internal developed repositories.
Also word Paytrail must be changed written as it should.

**Comment by Matsuuu** [comment]
@Jipsukka Thanks for the reply!

Great to hear, that you are welcoming of third-party repositories!

As I see this as a green light to develop the component further, I will proceed on the development of the component, the UX regarding the component and the docs of the component.

I will inform you when I see it in a state ready for release, and then we can see into transferring the component under the Paytrail repositories, and publish it in NPM. 


I'll gladly take care of updating the component and handling bugs regarding it. I will also try to write extensive documentation and a "Cookbook" of sorts on how to use the component in different environments.

**Comment by Matsuuu** [comment]
Hi @Jipsukka , 

I've made the updates to the code base you've requested: Changing the naming from "PayTrail" to "Paytrail".

I also refactored the code base a bit to make the component more customizable.

The examples in this PR are slightly outdated now, and I would like the project added to the Paytrail namespace, and published under the Paytrail npm repo before I fix the examples, since that way the examples can be shown using the Paytrail -owned npm package.

If there's some disclaimers, that need to be added to the repository's README etc, could you please submit a PR to my repository or update it with the correct disclaimers after the namespace change?

**Comment by Matsuuu** [comment]
Hi @Jipsukka , Nudging this again :)

**Comment by Jipsukka** [comment]
@Matsuuu
Can you send me email, so I can include every participant in discussion, now I have to play broken phone on this matter and it seems not be working well enough.
juho-pekka.vuorela@paytrail.com

**Comment by Jipsukka** [comment]
This is no longer relevant since repository is in under Paytrail and repository itself can contain all possible examples with better details in README or separate example.

**Pull request closed without merging**
